# Generated by Django 5.1.7 on 2025-07-28 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('A', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('B', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('C', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('D', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LoungerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lounger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10)),
                ('is_obstacle', models.BooleanField(default=False)),
                ('lounger_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.loungertype')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.stage')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Slobodno'), ('unavailable', 'Zauzeto'), ('reserved', 'Rezervisano'), ('signature', 'Potpis')], default='available', max_length=12)),
                ('date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lounger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.lounger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Slobodno'), ('unavailable', 'Zauzeto'), ('reserved', 'Rezervisano'), ('signature', 'Potpis')], default='available', max_length=12)),
                ('price', models.PositiveIntegerField(default=0)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='website.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('action', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='website.reservation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('date', 'lounger'), name='unique_date_lounger'),
        ),
        migrations.AddConstraint(
            model_name='lounger',
            constraint=models.UniqueConstraint(fields=('stage', 'lounger_type', 'position'), name='unique_lounger_position'),
        ),
    ]
