# Generated by Django 5.1.7 on 2025-08-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
