# Generated by Django 5.1.7 on 2025-08-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_reservationdetail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrevenue',
            name='busy_bed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyrevenue',
            name='busy_lounger',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyrevenue',
            name='reserver',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyrevenue',
            name='signature',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_reservations',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
