# Generated by Django 5.1.7 on 2025-08-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_dailyrevenue_busy_bed_dailyrevenue_busy_lounger_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrevenue',
            old_name='reserver',
            new_name='reserved',
        ),
    ]
