# Generated by Django 5.1.7 on 2025-08-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_reserver_dailyrevenue_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrevenue',
            name='busy_bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrevenue',
            name='busy_lounger',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrevenue',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrevenue',
            name='signature',
            field=models.IntegerField(default=0),
        ),
    ]
