# Generated by Django 5.1.7 on 2025-09-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_dailyrevenue_busy_bed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrevenue',
            name='reserved_bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyrevenue',
            name='reserved_lounger',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrevenue',
            name='A',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrevenue',
            name='B',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrevenue',
            name='C',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrevenue',
            name='D',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrevenue',
            name='total_income',
            field=models.IntegerField(default=0),
        ),
    ]
