# Generated by Django 5.1.7 on 2025-09-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_dailyrevenue_reserved_bed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrevenue',
            name='total_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyrevenue',
            name='total_loungers',
            field=models.IntegerField(default=0),
        ),
    ]
