# Generated by Django 5.1.7 on 2025-09-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_dailyrevenue_total_beds_dailyrevenue_total_loungers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='end_date',
        ),
    ]
