# Generated by Django 5.1.7 on 2025-08-04 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_stage'),
        ('website', '0005_alter_dailyrevenue_busy_bed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stage',
            field=models.ForeignKey(blank=True, default='A', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage', to='website.stage'),
        ),
    ]
